export const PICTURE_CREATE_REQUEST = 'PICTURE_CREATE_REQUEST'
export const PICTURE_CREATE_SUCCESS = 'PICTURE_CREATE_SUCCESS'
export const PICTURE_CREATE_FAIL = 'PICTURE_CREATE_FAIL'
export const PICTURE_CREATE_RESET = 'PICTURE_CREATE_RESET'