# Generated by Django 3.2.3 on 2021-10-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_alter_artpiece_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artpiece',
            old_name='artist',
            new_name='user',
        ),
    ]
